/* Copyright (C) 2013 Interactive Brokers LLC. All rights reserved.  This code is subject to the terms
 * and conditions of the IB API Non-Commercial License or the IB API Commercial License, as applicable. */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;

namespace IBApi.Interfaces
{
    /**
     * @class CommissionReport
     * @brief class representing the commissions generated by an execution.
     * @sa Execution
     */
    [ComVisible(true)]
    public interface ITwsCommissionReport : TWSLib.ICommissionReport
    {
       
        /**
        * @brief the execution's id this commission belongs to.
        */
        string ExecId { get; set; }

        /**
         * @brief the commissions cost.
         */
        double Commission { get; set; }

        /**
        * @brief the reporting currency.
        */
        string Currency { get; set; }

        /**
        * @brief the realised profit and loss
        */
        double RealizedPNL { get; set; }

        /**
         * @brief The income return.
         */
        double Yield { get; set; }

        /**
         * @brief date expressed in yyyymmdd format.
         */
        int YieldRedemptionDate { get; set; }

    }
}
